### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by obladon25** [oakcms/oakcms#1]
Warning: require(/home/parerea/public_html/oakcms.parerea.md/vendor/autoload.php): failed to open stream: No such file or directory in /home/parerea/public_html/oakcms.parerea.md/index.php on line 10

Fatal error: require(): Failed opening required '/home/parerea/public_html/oakcms.parerea.md/vendor/autoload.php' (include_path='.:/usr/lib/php:/usr/local/lib/php') in /home/parerea/public_html/oakcms.parerea.md/index.php on line 10

NOT directories )))

**Comment by hryvinskyi** [comment]
Excuse me. Not written in the instructions. You need to run [composer](https://getcomposer.org/download/).
Either run
`composer update`
